# Generated by Django 4.1 on 2022-08-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripción',
            name='Cantidad_de_integrantes',
            field=models.IntegerField(),
        ),
    ]
